#PVP世界中心點
center: world,-7,-60,-5
#死亡音效
deadMusic: 'minecraft:block.anvil.place'
#重生點範圍
spawn:
  R1: world,1,-53,-1
  R2: world,-16,-53,-16
#邊界
border:
  #剩餘幾秒開始縮圈置最小範圍(秒)
  time: 60
  #縮圈至指定範圍(半徑)
  minRadius: 8
  #遊戲開始最大範圍(半徑)
  maxRadius: 24
#遊戲開始設定
start:
  #每隊重生的最小距離
  minDistance: 2
  #每隊重生初始高度
  spawnY: 0
  #開始遊戲幾秒後顯示名稱
  showNameTimer: 60
  #剩餘幾秒後清除怪物(秒)
  clearMonsterTimer: 180
  #剩餘幾秒後全體玩家發光(秒)
  glowingTimer: 120
  #礦物懲罰
  punished:
    #最低礦物
    baselineThreshold: 800
    #每多少個礦物隨機給予狀態
    progressiveTriggerRule: 100
    #效果清單
    effects:
        #效果名稱
      - name: GLOWING
        #效果等級
        level: 0
        #效果時間(秒)
        time: 30
      - name: WEAKNESS
        level: 0
        time: 30
      - name: SLOW_DIGGING
        level: 0
        time: 30
      - name: SLOW
        level: 0
        time: 30
#特殊物品
specialItem:
    #種類
  - type: INSTANT_HEALTH_BOOK
    #編號
    key: ihb
    #物品名稱
    name: 生日快樂
    #物品材質
    material: BOOK
    #物品敘述
    lore:
      - ''
    #合成方式
    recipe:
      - 'AAA'
      - 'ABA'
      - 'AAA'
    #根據recipe設定對應的材質
    ingredient:
      A: GOLD_INGOT
      B: PLAYER_HEAD
    #恢復血量
    health: 10
    #獲得效果
    effects:
        #效果名稱
      - name: ABSORPTION
        #效果等級
        level: 0
        #效果時間(秒)
        time: 6
  - type: LUCKY_BLOCK
    key: lb
    name: 禮物箱
    material: STRIPPED_CHERRY_WOOD
    lore:
      - ''
    recipe:
      - 'AAA'
      - 'ABA'
      - 'AAA'
    ingredient:
      A: IRON_INGOT
      B: CHEST
    #隨機物品
    randomItem:
      - material: GOLD_INGOT
        chance: 100
        amount: 1
