#PVP世界中心點
center: world,353,188,-1986
#死亡音效冷卻時間(秒)
deadMusicCoolDown: 30
#死亡音效
deadMusic: 'minecraft:uhc.birthday'
#重生點範圍
spawn:
  R1: world,345,189,-1996
  R2: world,362,189,-1979
#邊界
border:
  #縮圈開始音效
  music: 'minecraft:uhc.padoru'
  #縮圈至指定範圍(直徑)
  minRadius: 10
  #遊戲開始最大範圍(直徑)
  maxRadius: 512
#遊戲開始設定
start:
  #每隊重生的最小距離
  minDistance: 100
  #每隊重生初始高度
  spawnY: 160
  #開始遊戲幾秒後顯示名稱
  showNameTimer: 20
  #剩餘幾秒後清除怪物(秒)
  clearMonsterTimer: 240
  #剩餘幾秒後全體玩家發光(秒)
  glowingTimer: 180
  #礦物懲罰
  punished:
    #最低礦物
    baselineThreshold: 800
    #每多少個礦物隨機給予狀態
    progressiveTriggerRule: 100
    #效果清單
    effects:
      #效果名稱
      - name: GLOWING
        #效果等級
        level: 0
        #效果時間(秒)
        time: 30
      - name: WEAKNESS
        level: 0
        time: 30
      - name: SLOW_DIGGING
        level: 0
        time: 30
      - name: SLOW
        level: 0
        time: 30
#特殊物品
specialItem:
  #種類
  - type: INSTANT_HEALTH_BOOK
    #編號
    key: ihb
    #物品名稱
    name: 生日快樂
    #物品材質
    material: BOOK
    #物品敘述
    lore:
      - ''
    #合成方式
    recipe:
      - 'AAA'
      - 'ABA'
      - 'AAA'
    #根據recipe設定對應的材質
    ingredient:
      A: GOLD_INGOT
      B: PLAYER_HEAD
    #恢復血量
    health: 0
    #獲得效果
    effects:
      #效果名稱
      - name: ABSORPTION
        #效果等級
        level: 0
        #效果時間(秒)
        time: 6
        #效果名稱
      - name: REGENERATION
        #效果等級
        level: 2
        #效果時間(秒)
        time: 5
  - type: LUCKY_BLOCK
    key: lb
    name: 禮物箱
    material: STRIPPED_CHERRY_WOOD
    lore:
      - ''
    recipe:
      - 'AAA'
      - 'ABA'
      - 'AAA'
    ingredient:
      A: IRON_INGOT
      B: CHEST
    #隨機物品
    randomItem:
      - material: STONE
        chance: 20
        amount: 64
      - material: SPRUCE_PLANKS
        chance: 20
        amount: 16
      - material: APPLE
        chance: 10
        amount: 8
      - material: LAPIS_LAZULI
        chance: 8
        amount: 16
      - material: COAL
        chance: 10
        amount: 16
      - material: IRON_INGOT
        chance: 8
        amount: 16
      - material: LEATHER_CHESTPLATE
        chance: 10
        amount: 1
      - material: LEATHER
        chance: 8
        amount: 1
      - material: WOODEN_SWORD
        chance: 10
        amount: 1
      - material: STONE_SWORD
        chance: 10
        amount: 1
      - material: GOLDEN_SWORD
        chance: 8
        amount: 1
      - material: IRON_SWORD
        chance: 8
        amount: 1
      - material: BOW
        chance: 8
        amount: 1
      - material: ARROW
        chance: 10
        amount: 32
      - material: COPPER_INGOT
        chance: 10
        amount: 16
      - material: REDSTONE
        chance: 10
        amount: 16
      - material: COOKED_BEEF
        chance: 10
        amount: 16
      - material: ROTTEN_FLESH
        chance: 10
        amount: 16
      - material: FISHING_ROD
        chance: 8
        amount: 1
      - material: PAPER
        chance: 10
        amount: 16
      - material: CAKE
        chance: 8
        amount: 1
      - material: WATER_BUCKET
        chance: 8
        amount: 1
      - material: BONE_MEAL
        chance: 10
        amount: 16
      - material: STRING
        chance: 8
        amount: 16
      - material: HORSE_SPAWN_EGG
        chance: 5
        amount: 1
      - material: IRON_CHESTPLATE
        chance: 5
        amount: 1
      - material: POTION
        chance: 5
        amount: 1
        effects:
          - name: SPEED
            level: 0
            time: 30
      - material: SPLASH_POTION
        chance: 5
        amount: 1
        effects:
          - name: WEAKNESS
            level: 0
            time: 20
      - material: POTION
        chance: 5
        amount: 1
        effects:
          - name: JUMP
            level: 0
            time: 30
      - material: ENDER_PEARL
        chance: 5
        amount: 2
      - material: OBSIDIAN
        chance: 5
        amount: 4
      - material: GOLDEN_CHESTPLATE
        chance: 5
        amount: 1
      - material: GOLD_INGOT
        chance: 5
        amount: 8
      - material: DIAMOND
        chance: 2
        amount: 4
      - material: LAVA_BUCKET
        chance: 2
        amount: 1
      - material: DIAMOND_CHESTPLATE
        chance: 2
        amount: 1
      - material: GOLDEN_APPLE
        chance: 2
        amount: 1
      - material: DIAMOND_SWORD
        chance: 2
        amount: 1
      - material: TNT
        chance: 2
        amount: 1
      - material: CREEPER_SPAWN_EGG
        chance: 2
        amount: 1
      - material: POTION
        chance: 2
        amount: 1
        effects:
          - name: HEAL
            level: 0
            time: 1
